version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:8080:8080"
      # Also expose on port 3000 as alternative
      - "0.0.0.0:3000:8080"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - PGUSER=postgres
      - PGHOST=db
      - PGPASSWORD=postgres
      - PGDATABASE=postgres
      - PGPORT=5432
      - NODE_ENV=production
      # Adding explicit DEBUG environment variable
      - DEBUG=express:*
    # Use default network mode for better host connectivity
    # network_mode: "bridge"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    # Disable healthcheck initially for debugging
    healthcheck:
      test: ["CMD", "curl", "-v", "http://localhost:8080/api/tasks"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_data: